export const Strings = {
  app: {
    name: 'FamilyWin',
    tagline: 'Chores. Discipline. Champions.',
  },

  auth: {
    login: 'Log In',
    register: 'Create Account',
    logout: 'Log Out',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    signUp: 'Sign Up',
    signIn: 'Sign In',
  },

  family: {
    createFamily: 'Create Family',
    joinFamily: 'Join Family',
    familyName: 'Family Name',
    inviteCode: 'Invite Code',
    yourName: 'Your Name',
    yourAge: 'Your Age (optional)',
    role: 'Role',
    parent: 'Parent',
    child: 'Child',
    adminParent: 'Admin Parent',
    copied: 'Invite code copied!',
    inviteMembers: 'Invite Members',
  },

  tasks: {
    title: 'Tasks',
    todaysTasks: "Today's Tasks",
    createTask: 'Create Task',
    editTask: 'Edit Task',
    taskTitle: 'Task Title',
    taskDescription: 'Description (optional)',
    category: 'Category',
    difficulty: 'Difficulty',
    recurrence: 'Repeats',
    assignTo: 'Assign To',
    anyone: 'Anyone',
    pointValue: 'Points',
    autoFailHour: 'Auto-fail at',
    markDone: 'Mark Done',
    completed: 'Completed ✓',
    failed: 'Auto-failed',
    noTasksToday: 'No tasks for today! 🎉',
    allDone: 'All done for today! 🏆',
  },

  points: {
    points: 'pts',
    earned: 'earned',
    lost: 'lost',
    thisWeek: 'This Week',
    allTime: 'All Time',
    history: 'Point History',
  },

  leaderboard: {
    title: 'Leaderboard',
    weeklyStandings: 'Weekly Standings',
    rank: 'Rank',
    winner: 'Winner! 🏆',
    noMembers: 'No members yet',
  },

  discipline: {
    title: 'Discipline',
    logEvent: 'Log Event',
    selectMember: 'Select Member',
    reason: 'Reason',
    pointChange: 'Point Change',
    note: 'Note (optional)',
    penalty: 'Penalty',
    bonus: 'Bonus',
    logDiscipline: 'Log Discipline',
  },

  rewards: {
    title: 'Rewards',
    store: 'Rewards Store',
    createReward: 'Create Reward',
    redeem: 'Redeem',
    pointCost: 'Point Cost',
    pending: 'Pending',
    approved: 'Approved ✓',
    rejected: 'Rejected',
    notEnoughPoints: "You don't have enough points",
    redeemed: 'Redeemed!',
  },

  notifications: {
    dailyReminderTitle: '📋 Task Check-in Time!',
    dailyReminderBody: "Don't forget to mark today's tasks done or you'll lose points!",
    weeklyWinnerTitle: '🏆 Weekly Results Are In!',
    streakTitle: '🔥 Keep your streak going!',
    missedTasksTitle: '⚠️ Missed tasks alert',
  },

  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Retry',
    noData: 'No data yet',
    comingSoon: 'Coming Soon',
    settings: 'Settings',
    profile: 'Profile',
    history: 'History',
  },

  errors: {
    required: 'This field is required',
    invalidEmail: 'Invalid email address',
    passwordTooShort: 'Password must be at least 6 characters',
    invalidInviteCode: 'Invalid invite code',
    networkError: 'Network error. Please try again.',
    authError: 'Authentication failed. Please try again.',
  },
} as const;
